select * from Customer;
select * from Rooms;
select * from Payment;
select * from Booking;
select * from BOOKINGROOMS;
select * from Employes;
select * from Activities;
select * from Bookingactivities;
select * from Work;
